### ISSUE TITLE
Where to drop my markdown files

### ISSUE THREAD

**Issue by kevinmoilar** [mattwaler/tea-stack#3]
Hey Matt. I don't know much about js so I struggle to reverse-engineer this. Where do I put my markdown files / my content to build a working site, so the index files generated from the .md files includes the necessary headers? I would appreciate a small addition to the README with a hint in that direction. Cheers, Kevin

**Comment by mattwaler** [comment]
Hello @kevinmoilar !

You can drop your markdown files anywhere you would like inside the `src` directory to create pages!

Just make sure you are adding a `layout` key in your frontmatter so that you can utilize your templates. For example:

```md
---
title: New Page
layout: layout
---

# Markdown content here!

```

I would consult the [11ty docs](https://www.11ty.dev/docs/) for more information on how to best use that portion of the stack. I also have an old [archived project](https://github.com/mattwaler/mattwaler-tea/tree/master/src/blog) that is using markdown files as well if you want to consult that!

I also provide a [paid instruction service](https://overpass.mattwaler.com) so if you would like to schedule a session to deep dive into 11ty I'd be happy to show you around!
